# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/command_module.html
- name: "Setup MySQL for wpS"
  command: /tmp/setup-mysql.sh

  ---
  - name: Update the software package repository
    command: yum update -y

  - name: Install mysql
    yum:
      state: present
      name:
        - mysql
        - MySQL-python

  - name: "Create {{ rds_db_username }} database"
    mysql_db:
      name: "{{ rds_db_username }}"
      login_host: "{{ rds_db_host }}"
      login_port: "{{ rds_db_port }}"
      login_user: "{{ rds_db_username }}"
      login_password: "{{ rds_db_password }}"
      state: present